### ISSUE TITLE
Configure oData Feed from Socrata

### ISSUE THREAD

**Issue by brianavecchione** [BetaNYC/BoardStat#14]
Socrata has agreed to let us be the first beta testers to use filtered odata feeds for Power BI. Unfortunately, as of last week, the given filtered URL still produced import errors on our end. Configuring oData is an obvious priority so that CBs can have near-real-time dashboards.

**Comment by brianavecchione** [comment]
Manually, it looks like the only thing that's worked (THUS FAR) is re-creating the slicer. This is clearly not sustainable overhead. What might be possible is creating a calculated field for the latest date and loading that into the slicer. 

DAX documentation [here](https://blogs.msdn.microsoft.com/lukaszp/2015/08/08/finding-the-latest-date-in-power-bi-desktop/)

**Comment by brianavecchione** [comment]
The difference in visualizations ended up being a data type issue between tables: To fix, copy 'created date' into a new column. Change the data type to 'Date' instead of 'Date/Time'. Then, drag the new field into the visualizations experiencing errors.

**Comment by noneck** [comment]
@brianavecchione leaving this tread open to document more Socrata / oData 500 error issues.

**Comment by noneck** [comment]
Closing this issue as we have addressed it and other ODATA issues have come up.
