### ISSUE TITLE
About Page Copy

### ISSUE THREAD

**Issue by brianavecchione** [BetaNYC/BoardStat#15]
BoardStat needs an about page so that users are able to better navigate the tool. There are two approaches to this:
- Modeling it similarly to an FAQ/references/glossary page, where a user can direct themselves to the page when they need assistance. This has a disadvantage in that use cases may not be immediately clear to users who are not familiar with BoardStat & it's purpose.
- Modeling it as a splash page that users see on load. This has the disadvantage of being repetitive (Do users really need a welcome page every time they visit?)

**Comment by noneck** [comment]
Added on 0.5d.
