### ISSUE TITLE
311 Reports from Marble Hill shown in CB8 page

### ISSUE THREAD

**Issue by RichPrescott** [BetaNYC/BoardStat#24]
If you open the CB8 Boardstat page, it will include 311 reports from Marble Hill.  This land is special in that it is technically considered part of Manhattan (the river was rerouted), but is part of Bronx CBs 7/8.

**Comment by noneck** [comment]
We are aware of this issue. This is something that is coming from City Planning's tools. :-(

**Comment by noneck** [comment]
I've reported this to DOITT.
