### ISSUE TITLE
Address Lookup table Date fields

### ISSUE THREAD

**Issue by RichPrescott** [BetaNYC/BoardStat#25]
The table on Page 2 of the report lists the Year/Month/Day twice and in separate fields.  This is redundant and makes sorting by Date difficult.  For this table, the Date should be shown without hierarchy.

**Comment by noneck** [comment]
@RichPrescott i've updated the view to only have "created date" not sure if "close" date was needed. Also, I placed the sort as descending on date. Let me know if you think this is more useful.

**Comment by noneck** [comment]
Closing
