### ISSUE TITLE
Review training materials with a 5 borough viewpoint.

### ISSUE THREAD

**Issue by noneck** [BetaNYC/BoardStat#38]
@prathmj - review the [data journey](http://bit.ly/boardstat_worksheet_v1) worksheet for the following issues:
 * grammar, now — that we have five borough views, does the language still make sense
 * 5 borough-ness, what are the other complaint type stories we should consider adding as data journeys. NOTE, #36 will affect your insights.
 * what else are you seeing?

Please use built-in comments via google docs and comments here on github.

**Comment by prathmj** [comment]
The first data journey is incompatible with the other Boroughs (see Google Doc for more information). Need to think of a new one to replace the current Noise-Construction one.

**Comment by noneck** [comment]
@prathmj - before closing this out, can you read it again for acronyms and add them to the glossary.
