### ISSUE TITLE
Version 0.6b Changelog

### ISSUE THREAD

**Issue by prathmj** [BetaNYC/BoardStat#84]
#81: Reordered first page
#82: Reordered the top bar on every page
#49: Added clear all buttons to the top bar
#71: Added ability to select multiple addresses on Page 2
#83: Recolored Page 4
#77: Added the “Complaints Over Time” and “Compare Complaint Types” pages (to eventually replace “Service Requests by Year” and “Complaint Type by Month”)

**Comment by noneck** [comment]
@prathmj Thanks for making these changes. I've updated the change log and am closing this ticket.
